### ISSUE TITLE
Rewriting repository history.

### ISSUE THREAD

**Issue by victorlapshev** [protocolbuffers/protobuf-php#1]
Did you rewrite history, so commit 66dc42d891a4fc8e9190c524fd67961688a37bbe is not avail anymore?

**Comment by SimoneStefani** [comment]
Seems so:
```
- Installing google/protobuf (v3.6.1.3): Downloading (0%)    Failed to download google/protobuf from dist: The "https://codeload.github.com/protocolbuffers/protobuf-php/legacy.zip/66dc42d891a4fc8e9190c524fd67961688a37bbe" file could not be downloaded (HTTP/1.1 404 Not Found)
  Now trying to download from source

- Installing google/protobuf (v3.6.1.3): Cloning 66dc42d891 from cache
  66dc42d891a4fc8e9190c524fd67961688a37bbe is gone (history was rewritten?)

  [RuntimeException]                                                                                                                              
  Failed to execute git checkout '66dc42d891a4fc8e9190c524fd67961688a37bbe' -- && git reset --hard '66dc42d891a4fc8e9190c524fd67961688a37bbe' --  

  fatal: reference is not a tree: 66dc42d891a4fc8e9190c524fd67961688a37bbe 
```

**Comment by aaronkaz** [comment]
I just encountered this while updating dependencies on a project.

in composer.lock before...

```
"name": "google/protobuf",
"version": "v3.6.1.3",
"source": {
    "type": "git",
    "url": "https://github.com/protocolbuffers/protobuf.git",
    "reference": "66dc42d891a4fc8e9190c524fd67961688a37bbe"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/protocolbuffers/protobuf/zipball/66dc42d891a4fc8e9190c524fd67961688a37bbe",
    "reference": "66dc42d891a4fc8e9190c524fd67961688a37bbe",
    "shasum": ""
},
```

after...

```
"name": "google/protobuf",
"version": "v3.6.1.3",
"source": {
    "type": "git",
    "url": "https://github.com/protocolbuffers/protobuf-php.git",
    "reference": "c39346815303f63ad295d6499e11d914c40040e6"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/c39346815303f63ad295d6499e11d914c40040e6",
    "reference": "c39346815303f63ad295d6499e11d914c40040e6",
    "shasum": ""
},
```

Then I saw error in my tests:
```
Fatal error: Class 'Google\Protobuf\Internal\Message' not found
```

Do I just need to re-create the protobuf php files from the original .proto file if I want this upgrade?

**Comment by tab1293** [comment]
@TeBoring can you explain why history was rewritten for this repository?

**Comment by yuloh** [comment]
We are running into the same issue.  What happened for us is composer update some/other-package` automatically rewrote `https://api.github.com/repos/google/protobuf/zipball/b5fbb742af122b565925987e65c089577399
76a7` to `https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/b5fbb742af122b565925987e65c08957739976a7` in `composer.lock`.  Afterwards `composer install` fails with the following message:

```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing google/protobuf (v3.5.2): Downloading (failed)    Failed to download google/protobuf from dist: The "https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/b5fbb742af122b565925987e65c08957739976a7" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source
  - Installing google/protobuf (v3.5.2): Cloning b5fbb742af from cache
    b5fbb742af122b565925987e65c08957739976a7 is gone (history was rewritten?)
```

`composer update google/protobuf` seems to resolve the issue (the tag for `v3.5.2` is updated to `801d776b4e4c9fce294d800974266c616bb2ce40`).

**Comment by TeBoring** [comment]
We recently created this protobuf-php to contain only php related code and point Packagist to this new repo.
In this way, composer users don't need to depend on all protobuf code (e.g., java, objc, etc).
Although, the checksum is different, the content is the same. Please update your composer.lock.

**Comment by yuloh** [comment]
@aaronkaz the autoloading path was changed from `php/src/Google/Protobuf` to `src/Google/Protobuf`.  If you are getting that error it's likely your `composer.lock` still has the old autoloading path.

The simplest solution is to call `composer update google/protobuf`, which will update `composer.lock` with the new autoload path.

**Comment by yuloh** [comment]
I understand the benefit of the new repository but it seems like this could have been done without breaking everyone's builds?

Composer will update the repository URL in `composer.lock` automatically when you run any `composer` commands.  It expects the same commits to be available at the new URL so it does not update the `reference` hash.  The next `composer install` will unexpectedly fail because it's trying to download an old hash from the new repository URL.

One way to handle this situation if you can't import the existing commits is to mark the package as [abandoned](https://getcomposer.org/doc/04-schema.md#abandoned) and create a new package.  If `google/protobuf` was marked abandoned and suggested `protocolbuffers/protobuf-php` as a replacement it would have allowed users to update the composer requirement at their earliest convenience.  The [replace](https://getcomposer.org/doc/04-schema.md#replace) config is also helpful for this.

Alternatively it seems like the existing history from `google/protobuf` could have been kept when creating this repository and then the new structure could be used for any new tags.

Unfortunately composer doesn't handle rewriting history well and they close any issues to improve it because they [consider it a bad practice](https://github.com/composer/composer/issues/1496#issuecomment-12417872).

**Comment by Shylajhaa** [comment]
I tried running `composer update google/protobuf`
Still, I get the same error
```
[RuntimeException]                                                                                                                              
  Failed to execute git checkout '860bd12fec5c69e6529565165532b3d5108a7d97' -- && git reset --hard '860bd12fec5c69e6529565165532b3d5108a7d97' --  
                                                                                                                                                  
  fatal: reference is not a tree: 860bd12fec5c69e6529565165532b3d5108a7d97
```

**Comment by victorlapshev** [comment]
> I tried running `composer update google/protobuf`
> Still, I get the same error
> 
> ```
> [RuntimeException]                                                                                                                              
>   Failed to execute git checkout '860bd12fec5c69e6529565165532b3d5108a7d97' -- && git reset --hard '860bd12fec5c69e6529565165532b3d5108a7d97' --  
>                                                                                                                                                   
>   fatal: reference is not a tree: 860bd12fec5c69e6529565165532b3d5108a7d97
> ```

`composer clear-cache`

**Comment by techcyclist** [comment]
The `composer update google/protobuf` worked for me. I'm deploying laravel via Envoyer and added this as a deployment hook after cloning the repo.

**Comment by M1ke** [comment]
This has now happened to me for the second time because another library that depended on a changed hash overwrote our lock file hash given the versions were meant to be the same. Changing repository history is a gift that keeps on giving...
